import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { RandomTable, TableRollResult } from '../types'

const BUILT_IN_TABLES: RandomTable[] = [
  {
    id: 'weather',
    name: 'Weather',
    category: 'Environment',
    dieType: 12,
    custom: false,
    rows: [
      { min: 1, max: 1, result: 'Heavy fog, visibility severely reduced' },
      { min: 2, max: 2, result: 'Torrential rain, paths become muddy' },
      { min: 3, max: 3, result: 'Thunderstorm with lightning' },
      { min: 4, max: 5, result: 'Light rain, overcast skies' },
      { min: 6, max: 6, result: 'Bitterly cold, risk of frostbite' },
      { min: 7, max: 7, result: 'Strong winds, difficult to travel' },
      { min: 8, max: 8, result: 'Overcast but dry' },
      { min: 9, max: 10, result: 'Partly cloudy, pleasant' },
      { min: 11, max: 11, result: 'Clear and sunny' },
      { min: 12, max: 12, result: 'Eerily calm, unsettling stillness' },
    ],
  },
  {
    id: 'encounter',
    name: 'Wilderness Encounter',
    category: 'Encounter',
    dieType: 20,
    custom: false,
    rows: [
      { min: 1, max: 1, result: 'Ambush! Bandits spring from hiding' },
      { min: 2, max: 2, result: 'Pack of wolves, hungry and circling' },
      { min: 3, max: 3, result: 'Wounded traveler begging for aid' },
      { min: 4, max: 4, result: 'Abandoned campfire, still warm' },
      { min: 5, max: 5, result: 'Merchant with unusual wares' },
      { min: 6, max: 7, result: 'Patrol of guards, suspicious' },
      { min: 8, max: 8, result: 'A strange shrine, offerings left' },
      { min: 9, max: 9, result: 'Giant spider web across the path' },
      { min: 10, max: 10, result: 'Skeleton half-buried in the earth' },
      { min: 11, max: 11, result: 'Hermit who knows local secrets' },
      { min: 12, max: 12, result: 'Dire boar, aggressive' },
      { min: 13, max: 13, result: 'Lost child, afraid' },
      { min: 14, max: 14, result: 'Sign of recent battle, bodies' },
      { min: 15, max: 15, result: 'Glowing mushroom ring, fey portal?' },
      { min: 16, max: 16, result: 'Patrol of undead, mindless' },
      { min: 17, max: 17, result: 'Damaged bridge, must find a way' },
      { min: 18, max: 18, result: 'Strange tracks, unknown creature' },
      { min: 19, max: 19, result: 'Thieves guild scouts' },
      { min: 20, max: 20, result: 'Dragon sighting overhead!' },
    ],
  },
  {
    id: 'dungeon-room',
    name: 'Dungeon Room',
    category: 'Dungeon',
    dieType: 12,
    custom: false,
    rows: [
      { min: 1, max: 1, result: 'Guard chamber, armed skeletons' },
      { min: 2, max: 2, result: 'Collapsed ceiling, rubble blocks half the room' },
      { min: 3, max: 3, result: 'Treasure vault, locked and trapped' },
      { min: 4, max: 4, result: 'Pit trap with iron spikes' },
      { min: 5, max: 5, result: 'Torture chamber with old implements' },
      { min: 6, max: 6, result: 'Flooded room, waist-deep black water' },
      { min: 7, max: 7, result: 'Shrine to a dark god' },
      { min: 8, max: 8, result: 'Barracks, sleeping monsters' },
      { min: 9, max: 9, result: 'Kitchen or larder, supplies & vermin' },
      { min: 10, max: 10, result: 'Alchemist\'s lab, bubbling experiments' },
      { min: 11, max: 11, result: 'Throne room, grand and silent' },
      { min: 12, max: 12, result: 'Secret door concealed in the wall' },
    ],
  },
  {
    id: 'npc-trait',
    name: 'NPC Trait',
    category: 'NPC',
    dieType: 20,
    custom: false,
    rows: [
      { min: 1, max: 1, result: 'Paranoid, trusts nobody' },
      { min: 2, max: 2, result: 'Greedy, everything has a price' },
      { min: 3, max: 3, result: 'Kind but naive' },
      { min: 4, max: 4, result: 'Secretly working for the enemy' },
      { min: 5, max: 5, result: 'Grieving a recent loss' },
      { min: 6, max: 6, result: 'Arrogant, underestimates others' },
      { min: 7, max: 7, result: 'Desperately in debt' },
      { min: 8, max: 8, result: 'Deeply religious, zealous' },
      { min: 9, max: 9, result: 'Former adventurer, retired' },
      { min: 10, max: 10, result: 'Speaks in riddles and metaphor' },
      { min: 11, max: 11, result: 'Fearful of a specific monster' },
      { min: 12, max: 12, result: 'Loyal to a fault' },
      { min: 13, max: 13, result: 'Harbors a dark secret' },
      { min: 14, max: 14, result: 'Obsessed with collecting something' },
      { min: 15, max: 15, result: 'Cheerful despite hardship' },
      { min: 16, max: 16, result: 'Looking for a missing person' },
      { min: 17, max: 17, result: 'Disguised noble or royalty' },
      { min: 18, max: 18, result: 'Has prophetic dreams' },
      { min: 19, max: 19, result: 'Master of a useful craft' },
      { min: 20, max: 20, result: 'Not entirely human' },
    ],
  },
  {
    id: 'loot',
    name: 'Treasure Loot',
    category: 'Loot',
    dieType: 20,
    custom: false,
    rows: [
      { min: 1, max: 3, result: 'Copper coins (2d10 cp)' },
      { min: 4, max: 6, result: 'Silver coins (1d20 sp)' },
      { min: 7, max: 8, result: 'Gold coins (1d10 gp)' },
      { min: 9, max: 9, result: 'Gemstone (roll d6: 1-2 quartz, 3-4 amethyst, 5 ruby, 6 diamond)' },
      { min: 10, max: 10, result: 'Ornate jewelry, worth 1d6 × 10 gp' },
      { min: 11, max: 11, result: 'Potion of healing (2d4+2)' },
      { min: 12, max: 12, result: 'Scroll with a random spell' },
      { min: 13, max: 13, result: '+1 weapon, roll for type' },
      { min: 14, max: 14, result: 'Armor or shield, masterwork' },
      { min: 15, max: 15, result: 'Magic ring, unknown effect' },
      { min: 16, max: 16, result: 'Mysterious map to a location' },
      { min: 17, max: 17, result: 'Arcane focus or holy symbol' },
      { min: 18, max: 18, result: 'Cursed item in disguise' },
      { min: 19, max: 19, result: 'Rare crafting material' },
      { min: 20, max: 20, result: 'Legendary artifact (GM decides)' },
    ],
  },
  {
    id: 'plot-twist',
    name: 'Plot Twist',
    category: 'Story',
    dieType: 10,
    custom: false,
    rows: [
      { min: 1, max: 1, result: 'A trusted ally betrays you' },
      { min: 2, max: 2, result: 'The enemy is not who you thought' },
      { min: 3, max: 3, result: 'A long-dead figure returns' },
      { min: 4, max: 4, result: 'The treasure is cursed or fake' },
      { min: 5, max: 5, result: 'You are being hunted as well' },
      { min: 6, max: 6, result: 'A third faction enters the conflict' },
      { min: 7, max: 7, result: 'The location is not what it seemed' },
      { min: 8, max: 8, result: 'Someone is using you as a pawn' },
      { min: 9, max: 9, result: 'A ticking clock is revealed' },
      { min: 10, max: 10, result: 'The truth was in front of you all along' },
    ],
  },
  {
    id: 'action-meaning',
    name: 'Action Meaning (Oracle)',
    category: 'Oracle',
    dieType: 100,
    custom: false,
    rows: [
      { min: 1, max: 2, result: 'Attainment' },
      { min: 3, max: 4, result: 'Starting' },
      { min: 5, max: 6, result: 'Neglect' },
      { min: 7, max: 8, result: 'Fight' },
      { min: 9, max: 10, result: 'Recruit' },
      { min: 11, max: 12, result: 'Triumph' },
      { min: 13, max: 14, result: 'Violate' },
      { min: 15, max: 16, result: 'Oppose' },
      { min: 17, max: 18, result: 'Restore' },
      { min: 19, max: 20, result: 'Oppress' },
      { min: 21, max: 22, result: 'Release' },
      { min: 23, max: 24, result: 'Befriend' },
      { min: 25, max: 26, result: 'Judge' },
      { min: 27, max: 28, result: 'Desert' },
      { min: 29, max: 30, result: 'Dominate' },
      { min: 31, max: 32, result: 'Procrastinate' },
      { min: 33, max: 34, result: 'Praise' },
      { min: 35, max: 36, result: 'Carry' },
      { min: 37, max: 38, result: 'Borrow' },
      { min: 39, max: 40, result: 'Expose' },
      { min: 41, max: 42, result: 'Haggle' },
      { min: 43, max: 44, result: 'Attack' },
      { min: 45, max: 46, result: 'Understand' },
      { min: 47, max: 48, result: 'Harm' },
      { min: 49, max: 50, result: 'Debase' },
      { min: 51, max: 52, result: 'Transform' },
      { min: 53, max: 54, result: 'Overthrow' },
      { min: 55, max: 56, result: 'Inform' },
      { min: 57, max: 58, result: 'Disrupt' },
      { min: 59, max: 60, result: 'Help' },
      { min: 61, max: 62, result: 'Pursue' },
      { min: 63, max: 64, result: 'Inspect' },
      { min: 65, max: 66, result: 'Arrive' },
      { min: 67, max: 68, result: 'Communicate' },
      { min: 69, max: 70, result: 'Take' },
      { min: 71, max: 72, result: 'Spy' },
      { min: 73, max: 74, result: 'Collect' },
      { min: 75, max: 76, result: 'Reduce' },
      { min: 77, max: 78, result: 'Protect' },
      { min: 79, max: 80, result: 'Create' },
      { min: 81, max: 82, result: 'Discover' },
      { min: 83, max: 84, result: 'Suppress' },
      { min: 85, max: 86, result: 'Abandon' },
      { min: 87, max: 88, result: 'Record' },
      { min: 89, max: 90, result: 'Bestow' },
      { min: 91, max: 92, result: 'Talk' },
      { min: 93, max: 94, result: 'Warn' },
      { min: 95, max: 96, result: 'Prepare' },
      { min: 97, max: 98, result: 'Trick' },
      { min: 99, max: 100, result: 'Confront' },
    ],
  },
  // ── NPC ───────────────────────────────────────────────────────────────────
  {
    id: 'npc-name-fantasy',
    name: 'NPC Name (Fantasy)',
    category: 'NPC',
    dieType: 20,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'Aldric the Scarred' },
      { min: 2,  max: 2,  result: 'Mirela Ashvale' },
      { min: 3,  max: 3,  result: 'Torund One-Eye' },
      { min: 4,  max: 4,  result: 'Sable Nightwhisper' },
      { min: 5,  max: 5,  result: 'Cormac of the Fens' },
      { min: 6,  max: 6,  result: 'Ysolde Fairbrow' },
      { min: 7,  max: 7,  result: 'Drak the Unmoved' },
      { min: 8,  max: 8,  result: 'Lirien Mossfoot' },
      { min: 9,  max: 9,  result: 'Hafnar Blackthorn' },
      { min: 10, max: 10, result: 'Tessaly Grim' },
      { min: 11, max: 11, result: 'Osvald the Crooked' },
      { min: 12, max: 12, result: 'Veyna Saltmarsh' },
      { min: 13, max: 13, result: 'Brom Ironfist' },
      { min: 14, max: 14, result: 'Isolde Ravenscar' },
      { min: 15, max: 15, result: 'Kael the Pale' },
      { min: 16, max: 16, result: 'Morwen Ashford' },
      { min: 17, max: 17, result: 'Selwyn Deepwater' },
      { min: 18, max: 18, result: 'Gundra Stoneback' },
      { min: 19, max: 19, result: 'Pell the Twice-Born' },
      { min: 20, max: 20, result: 'Riva Coldmere' },
    ],
  },
  {
    id: 'npc-goal',
    name: 'NPC Goal',
    category: 'NPC',
    dieType: 12,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'Seek revenge against a specific person' },
      { min: 2,  max: 2,  result: 'Protect a family member at all costs' },
      { min: 3,  max: 3,  result: 'Accumulate enough wealth to retire' },
      { min: 4,  max: 4,  result: 'Prove their worth to their peers' },
      { min: 5,  max: 5,  result: 'Find a lost artifact or heirloom' },
      { min: 6,  max: 6,  result: 'Escape a dangerous obligation or debt' },
      { min: 7,  max: 7,  result: 'Spread the word of their deity' },
      { min: 8,  max: 8,  result: 'Discover the truth about their origin' },
      { min: 9,  max: 9,  result: 'Become the most feared name in the region' },
      { min: 10, max: 10, result: 'Find a cure for a curse or disease' },
      { min: 11, max: 11, result: 'Live quietly and be left alone' },
      { min: 12, max: 12, result: 'Tear down a corrupt institution' },
    ],
  },
  {
    id: 'npc-secret',
    name: 'NPC Secret',
    category: 'NPC',
    dieType: 12,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'Is a wanted criminal under a false name' },
      { min: 2,  max: 2,  result: 'Killed someone close to the PC in the past' },
      { min: 3,  max: 3,  result: 'Is an informant for the local authorities' },
      { min: 4,  max: 4,  result: 'Carries a disease they\'re trying to hide' },
      { min: 5,  max: 5,  result: 'Is deeply in debt to dangerous people' },
      { min: 6,  max: 6,  result: 'Has a hidden second family elsewhere' },
      { min: 7,  max: 7,  result: 'Worships a forbidden or dark god' },
      { min: 8,  max: 8,  result: 'Is the rightful heir to something important' },
      { min: 9,  max: 9,  result: 'Sold out their companions to save themselves' },
      { min: 10, max: 10, result: 'Has a magical ability they keep hidden' },
      { min: 11, max: 11, result: 'Is being blackmailed by someone powerful' },
      { min: 12, max: 12, result: 'Was once on the opposing side of the conflict' },
    ],
  },
  {
    id: 'npc-occupation',
    name: 'NPC Occupation',
    category: 'NPC',
    dieType: 20,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'Traveling merchant with unusual stock' },
      { min: 2,  max: 2,  result: 'Disgraced soldier turned mercenary' },
      { min: 3,  max: 3,  result: 'Hedge witch / hedge wizard' },
      { min: 4,  max: 4,  result: 'Priest of an obscure deity' },
      { min: 5,  max: 5,  result: 'Guild thief or fence' },
      { min: 6,  max: 6,  result: 'Wandering bard or storyteller' },
      { min: 7,  max: 7,  result: 'Blacksmith or weaponsmith' },
      { min: 8,  max: 8,  result: 'Innkeeper with secrets' },
      { min: 9,  max: 9,  result: 'Bounty hunter' },
      { min: 10, max: 10, result: 'Scribe or lore keeper' },
      { min: 11, max: 11, result: 'Grave keeper or undertaker' },
      { min: 12, max: 12, result: 'Herbalist or apothecary' },
      { min: 13, max: 13, result: 'Corrupt tax collector' },
      { min: 14, max: 14, result: 'Retired adventurer turned guide' },
      { min: 15, max: 15, result: 'Spy or assassin in disguise' },
      { min: 16, max: 16, result: 'Sailor or river barge captain' },
      { min: 17, max: 17, result: 'Cult recruiter' },
      { min: 18, max: 18, result: 'Noble\'s disowned child' },
      { min: 19, max: 19, result: 'Monster hunter' },
      { min: 20, max: 20, result: 'Escaped slave seeking freedom' },
    ],
  },
  {
    id: 'npc-disposition',
    name: 'NPC Disposition',
    category: 'NPC',
    dieType: 10,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'Hostile — attacks or threatens immediately' },
      { min: 2,  max: 2,  result: 'Unfriendly — suspicious, gives nothing freely' },
      { min: 3,  max: 4,  result: 'Wary — will talk but keeps their distance' },
      { min: 5,  max: 6,  result: 'Neutral — business-like, transactional' },
      { min: 7,  max: 8,  result: 'Friendly — open, willing to help for a price' },
      { min: 9,  max: 9,  result: 'Helpful — genuinely wants to assist' },
      { min: 10, max: 10, result: 'Sycophantic — overly eager, possibly for bad reasons' },
    ],
  },

  // ── Environment ────────────────────────────────────────────────────────────
  {
    id: 'city-encounter',
    name: 'City / Town Encounter',
    category: 'Encounter',
    dieType: 20,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'A public execution is drawing a crowd' },
      { min: 2,  max: 2,  result: 'Pickpocket attempts to lift your coin purse' },
      { min: 3,  max: 3,  result: 'City guard checkpoint — papers demanded' },
      { min: 4,  max: 4,  result: 'A brawl spills out of a tavern doorway' },
      { min: 5,  max: 5,  result: 'A merchant is being publicly swindled' },
      { min: 6,  max: 6,  result: 'Festival or market day, crowds everywhere' },
      { min: 7,  max: 7,  result: 'A wanted poster — your face, or someone you know' },
      { min: 8,  max: 8,  result: 'Someone slips a note into your pocket' },
      { min: 9,  max: 9,  result: 'A body discovered in an alley' },
      { min: 10, max: 10, result: 'Noble\'s carriage nearly runs you down' },
      { min: 11, max: 11, result: 'Street preacher proclaims the end of days' },
      { min: 12, max: 12, result: 'Curfew bell rings — guards begin sweeping the streets' },
      { min: 13, max: 13, result: 'Someone begs you to hide them' },
      { min: 14, max: 14, result: 'A raven or crow follows you for hours' },
      { min: 15, max: 15, result: 'Guild enforcer watches you from a doorway' },
      { min: 16, max: 16, result: 'Child offers to guide you — for a price' },
      { min: 17, max: 17, result: 'Fire breaks out in a nearby building' },
      { min: 18, max: 18, result: 'Old acquaintance appears — badly wants a favor' },
      { min: 19, max: 19, result: 'Rat swarms pour from the sewers' },
      { min: 20, max: 20, result: 'Assassin was targeting you, kills the wrong person' },
    ],
  },
  {
    id: 'dungeon-dressing',
    name: 'Dungeon Dressing',
    category: 'Dungeon',
    dieType: 20,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'A rusted iron portcullis, jammed half-open' },
      { min: 2,  max: 2,  result: 'Crude graffiti in an unknown language' },
      { min: 3,  max: 3,  result: 'A shattered mirror in an ornate frame' },
      { min: 4,  max: 4,  result: 'Dried blood trail leading deeper in' },
      { min: 5,  max: 5,  result: 'Bones arranged in a deliberate pattern' },
      { min: 6,  max: 6,  result: 'A guttered torch still warm to the touch' },
      { min: 7,  max: 7,  result: 'Overturned table with scattered playing cards' },
      { min: 8,  max: 8,  result: 'Manacles chained to the wall, empty' },
      { min: 9,  max: 9,  result: 'Crude map scratched into the stone' },
      { min: 10, max: 10, result: 'A child\'s doll, inexplicably clean' },
      { min: 11, max: 11, result: 'Strange mold in the shape of a face' },
      { min: 12, max: 12, result: 'Coins of an ancient, unrecognized mint' },
      { min: 13, max: 13, result: 'A locked chest with no keyhole' },
      { min: 14, max: 14, result: 'Smell of sulfur and burnt hair' },
      { min: 15, max: 15, result: 'Faint sound of weeping from the walls' },
      { min: 16, max: 16, result: 'A trapdoor — leads somewhere unexpected' },
      { min: 17, max: 17, result: 'Hundreds of candles, all recently snuffed' },
      { min: 18, max: 18, result: 'Alchemical residue stains the floor' },
      { min: 19, max: 19, result: 'Torn journal page with partial instructions' },
      { min: 20, max: 20, result: 'A mirror that shows the room as it was years ago' },
    ],
  },
  {
    id: 'dungeon-hazard',
    name: 'Dungeon Hazard',
    category: 'Dungeon',
    dieType: 12,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'Pit trap — 10 ft. deep, spikes at the bottom' },
      { min: 2,  max: 2,  result: 'Poison dart trap triggered by a pressure plate' },
      { min: 3,  max: 3,  result: 'Slowly flooding room — water rising fast' },
      { min: 4,  max: 4,  result: 'Ceiling block descending — must escape quickly' },
      { min: 5,  max: 5,  result: 'Noxious gas pocket — save or be poisoned' },
      { min: 6,  max: 6,  result: 'Floor is unstable — risks collapse' },
      { min: 7,  max: 7,  result: 'Magic alarm — alerts all creatures in the area' },
      { min: 8,  max: 8,  result: 'Swinging blade trap across a corridor' },
      { min: 9,  max: 9,  result: 'Cursed rune on the floor — triggered on read' },
      { min: 10, max: 10, result: 'Web or slime blocking the passage' },
      { min: 11, max: 11, result: 'Reverse gravity zone — must navigate upside down' },
      { min: 12, max: 12, result: 'Magical darkness with no mundane light source' },
    ],
  },
  {
    id: 'tavern-scene',
    name: 'Tavern Scene',
    category: 'Encounter',
    dieType: 12,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'A drunk soldier is picking a fight with everyone' },
      { min: 2,  max: 2,  result: 'A card game in the corner — high stakes' },
      { min: 3,  max: 3,  result: 'Bard playing a song that hits a little too close to home' },
      { min: 4,  max: 4,  result: 'The innkeeper asks pointed questions about your business' },
      { min: 5,  max: 5,  result: 'A hooded figure in the corner watches you eat' },
      { min: 6,  max: 6,  result: 'Someone at the bar is clearly poisoned' },
      { min: 7,  max: 7,  result: 'A bounty hunter is asking about someone matching your description' },
      { min: 8,  max: 8,  result: 'Locals whisper about monster attacks nearby' },
      { min: 9,  max: 9,  result: 'A messenger arrives with urgent news for someone' },
      { min: 10, max: 10, result: 'The tavern runs out of food — suspiciously soon' },
      { min: 11, max: 11, result: 'Two factions about to come to blows over a table' },
      { min: 12, max: 12, result: 'A job offer is slipped under your mug' },
    ],
  },
  {
    id: 'terrain-feature',
    name: 'Wilderness Terrain Feature',
    category: 'Environment',
    dieType: 12,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'A collapsed stone bridge — river must be forded' },
      { min: 2,  max: 2,  result: 'Ancient standing stones humming faintly' },
      { min: 3,  max: 3,  result: 'Abandoned farmstead, ransacked recently' },
      { min: 4,  max: 4,  result: 'A crossroads with a gibbet' },
      { min: 5,  max: 5,  result: 'Dense thorns blocking the direct route' },
      { min: 6,  max: 6,  result: 'A cave mouth with drag marks outside' },
      { min: 7,  max: 7,  result: 'Cursed grove — animals refuse to enter' },
      { min: 8,  max: 8,  result: 'Ruined watchtower with a good view' },
      { min: 9,  max: 9,  result: 'A spring of clear water, suspiciously perfect' },
      { min: 10, max: 10, result: 'Sinkhole exposing ancient ruins below' },
      { min: 11, max: 11, result: 'A road shrine with fresh offerings' },
      { min: 12, max: 12, result: 'Unusual silence — no birds, no insects' },
    ],
  },

  // ── Combat ─────────────────────────────────────────────────────────────────
  {
    id: 'combat-complication',
    name: 'Combat Complication',
    category: 'Combat',
    dieType: 12,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'Reinforcements arrive for the enemy (roll encounter)' },
      { min: 2,  max: 2,  result: 'The ground gives way — everyone risks falling' },
      { min: 3,  max: 3,  result: 'Fire breaks out, spreading each round' },
      { min: 4,  max: 4,  result: 'A third party enters, hostile to both sides' },
      { min: 5,  max: 5,  result: 'Weapon or equipment breaks or jams' },
      { min: 6,  max: 6,  result: 'Darkness falls — torch extinguished or spell cast' },
      { min: 7,  max: 7,  result: 'Hostage taken — enemy demands surrender' },
      { min: 8,  max: 8,  result: 'Escape route is cut off' },
      { min: 9,  max: 9,  result: 'Something valuable is about to be destroyed' },
      { min: 10, max: 10, result: 'An ally acts against you (confused, charmed)' },
      { min: 11, max: 11, result: 'Environmental hazard triggers (trap, collapse)' },
      { min: 12, max: 12, result: 'The enemy reveals an unexpected power or form' },
    ],
  },
  {
    id: 'monster-tactic',
    name: 'Monster Tactic',
    category: 'Combat',
    dieType: 10,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'Charges recklessly at the nearest target' },
      { min: 2,  max: 2,  result: 'Flanks to attack from behind' },
      { min: 3,  max: 3,  result: 'Targets the most injured combatant' },
      { min: 4,  max: 4,  result: 'Focuses all attacks on the biggest threat' },
      { min: 5,  max: 5,  result: 'Tries to grapple or restrain' },
      { min: 6,  max: 6,  result: 'Retreats to gain range advantage' },
      { min: 7,  max: 7,  result: 'Uses the environment as cover' },
      { min: 8,  max: 8,  result: 'Calls for help from nearby allies' },
      { min: 9,  max: 9,  result: 'Feigns weakness then strikes hard' },
      { min: 10, max: 10, result: 'Flees if below half health' },
    ],
  },
  {
    id: 'injury',
    name: 'Injury / Wound',
    category: 'Combat',
    dieType: 12,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'Gashed leg — movement halved until treated' },
      { min: 2,  max: 2,  result: 'Sword arm wounded — −1 to attack rolls' },
      { min: 3,  max: 3,  result: 'Ribs cracked — disadvantage on strenuous actions' },
      { min: 4,  max: 4,  result: 'Eye scratched — ranged attacks at disadvantage' },
      { min: 5,  max: 5,  result: 'Hand crushed — cannot grip properly' },
      { min: 6,  max: 6,  result: 'Concussed — disadvantage on concentration' },
      { min: 7,  max: 7,  result: 'Shoulder dislocated — shield arm useless' },
      { min: 8,  max: 8,  result: 'Ear injury — deafened in one ear' },
      { min: 9,  max: 9,  result: 'Deep cut — loses 1 HP per round until bound' },
      { min: 10, max: 10, result: 'Knocked out briefly — lose next action' },
      { min: 11, max: 11, result: 'Armor damaged — AC reduced by 1' },
      { min: 12, max: 12, result: 'Glancing blow — shaken but unharmed this time' },
    ],
  },

  // ── Loot ───────────────────────────────────────────────────────────────────
  {
    id: 'magic-item',
    name: 'Magic Item',
    category: 'Loot',
    dieType: 20,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'Ring of feather falling' },
      { min: 2,  max: 2,  result: 'Cloak of shadows (+2 to stealth)' },
      { min: 3,  max: 3,  result: 'Boots of silent striding' },
      { min: 4,  max: 4,  result: 'Blade that glows near undead' },
      { min: 5,  max: 5,  result: 'Amulet of protection (+1 AC)' },
      { min: 6,  max: 6,  result: 'Bag of holding (small)' },
      { min: 7,  max: 7,  result: 'Wand with 1d6 charges of a random spell' },
      { min: 8,  max: 8,  result: 'Helm of detect thoughts (1/day)' },
      { min: 9,  max: 9,  result: 'Gauntlets of ogre strength (1 hour/day)' },
      { min: 10, max: 10, result: 'Mirror that reveals invisible creatures' },
      { min: 11, max: 11, result: 'Rope of climbing (50 ft., animates on command)' },
      { min: 12, max: 12, result: 'Stone of good luck (+1 to all saves)' },
      { min: 13, max: 13, result: 'Lantern of revealing (shows hidden doors)' },
      { min: 14, max: 14, result: 'Cursed blade: +2 attack, cannot be sheathed willingly' },
      { min: 15, max: 15, result: 'Pouch that always contains 1d6 cp (refills daily)' },
      { min: 16, max: 16, result: 'Dagger that returns when thrown' },
      { min: 17, max: 17, result: 'Belt of carrying (no encumbrance penalty)' },
      { min: 18, max: 18, result: 'Staff of striking (+1d6 on hit)' },
      { min: 19, max: 19, result: 'Pendant that warns of ambushes (tingles)' },
      { min: 20, max: 20, result: 'Artifact — roll on Plot Twist for its complications' },
    ],
  },
  {
    id: 'potion',
    name: 'Potion Type',
    category: 'Loot',
    dieType: 10,
    custom: false,
    rows: [
      { min: 1,  max: 2,  result: 'Healing (restores 2d4+2 HP)' },
      { min: 3,  max: 3,  result: 'Greater healing (restores 4d4+4 HP)' },
      { min: 4,  max: 4,  result: 'Poison antidote' },
      { min: 5,  max: 5,  result: 'Invisibility (1 hour)' },
      { min: 6,  max: 6,  result: 'Speed (double movement, extra action, 1 minute)' },
      { min: 7,  max: 7,  result: 'Strength (+4 STR for 1 hour)' },
      { min: 8,  max: 8,  result: 'Water breathing (1 hour)' },
      { min: 9,  max: 9,  result: 'Diminution (shrink to 6 inches, 1 hour)' },
      { min: 10, max: 10, result: 'Poison — save or take 3d6 damage (mislabeled!)' },
    ],
  },
  {
    id: 'gem',
    name: 'Gem & Jewel',
    category: 'Loot',
    dieType: 10,
    custom: false,
    rows: [
      { min: 1,  max: 2,  result: 'Quartz (1d4 sp)' },
      { min: 3,  max: 4,  result: 'Onyx (1d6 sp)' },
      { min: 5,  max: 6,  result: 'Amethyst (2d6 gp)' },
      { min: 7,  max: 7,  result: 'Garnet (3d6 gp)' },
      { min: 8,  max: 8,  result: 'Sapphire (5d6 gp)' },
      { min: 9,  max: 9,  result: 'Ruby (10d6 gp)' },
      { min: 10, max: 10, result: 'Diamond — flawless (50d6 gp)' },
    ],
  },

  // ── Story ──────────────────────────────────────────────────────────────────
  {
    id: 'adventure-hook',
    name: 'Adventure Hook',
    category: 'Story',
    dieType: 20,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'A child begs you to find their missing parent' },
      { min: 2,  max: 2,  result: 'A dying stranger presses a key into your hand' },
      { min: 3,  max: 3,  result: 'A map with an X falls out of a slain bandit\'s coat' },
      { min: 4,  max: 4,  result: 'A merchant offers double pay for a simple job — too simple' },
      { min: 5,  max: 5,  result: 'You\'re framed for a crime you didn\'t commit' },
      { min: 6,  max: 6,  result: 'An old enemy asks for your help — genuinely desperate' },
      { min: 7,  max: 7,  result: 'A letter arrives addressed to you but from the future' },
      { min: 8,  max: 8,  result: 'You inherit something valuable and immediately dangerous' },
      { min: 9,  max: 9,  result: 'A dream shows you a place you\'ve never been' },
      { min: 10, max: 10, result: 'Bounty on a monster — but locals worship it' },
      { min: 11, max: 11, result: 'Ancient tomb discovered under town construction' },
      { min: 12, max: 12, result: 'A cult is recruiting in the village and it\'s working' },
      { min: 13, max: 13, result: 'A noble hires you to retrieve something embarrassing' },
      { min: 14, max: 14, result: 'Strange lights seen on the mountain every night' },
      { min: 15, max: 15, result: 'The town well has run dry — and something is in it' },
      { min: 16, max: 16, result: 'A powerful NPC from the thread list needs something' },
      { min: 17, max: 17, result: 'You find a cache of supplies — someone needs them badly' },
      { min: 18, max: 18, result: 'A captured monster claims to have information' },
      { min: 19, max: 19, result: 'A thieves\' guild marks you as competition' },
      { min: 20, max: 20, result: 'A portal opens — something comes through, then closes' },
    ],
  },
  {
    id: 'scene-complication',
    name: 'Scene Complication',
    category: 'Story',
    dieType: 12,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'The goal turns out to be much harder than expected' },
      { min: 2,  max: 2,  result: 'An uninvited third party arrives with their own agenda' },
      { min: 3,  max: 3,  result: 'Something critical is missing or stolen' },
      { min: 4,  max: 4,  result: 'The person you need is not who they claimed to be' },
      { min: 5,  max: 5,  result: 'A time limit is introduced — act now or lose everything' },
      { min: 6,  max: 6,  result: 'Two threads from your list collide unexpectedly' },
      { min: 7,  max: 7,  result: 'Betrayal — someone you trusted works against you' },
      { min: 8,  max: 8,  result: 'The environment itself becomes a problem' },
      { min: 9,  max: 9,  result: 'Success would harm an innocent person' },
      { min: 10, max: 10, result: 'The situation is exactly backwards from what you expected' },
      { min: 11, max: 11, result: 'You uncover a much bigger conspiracy behind this one' },
      { min: 12, max: 12, result: 'A past action comes back to haunt you right now' },
    ],
  },
  {
    id: 'dungeon-purpose',
    name: 'Dungeon Purpose',
    category: 'Dungeon',
    dieType: 12,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'Ancient tomb of a forgotten king' },
      { min: 2,  max: 2,  result: 'Prison for a supernatural entity' },
      { min: 3,  max: 3,  result: 'Abandoned thieves\' guild headquarters' },
      { min: 4,  max: 4,  result: 'Alchemist\'s lab gone catastrophically wrong' },
      { min: 5,  max: 5,  result: 'Temple to a god now considered heretical' },
      { min: 6,  max: 6,  result: 'Dwarven delve that dug too deep' },
      { min: 7,  max: 7,  result: 'Smuggler network with hidden caches' },
      { min: 8,  max: 8,  result: 'Monster lair built over older ruins' },
      { min: 9,  max: 9,  result: 'Necromancer\'s sanctum, now abandoned' },
      { min: 10, max: 10, result: 'Fortification ruins from an ancient siege' },
      { min: 11, max: 11, result: 'Natural cave colonized by something hungry' },
      { min: 12, max: 12, result: 'Portal nexus to another plane, still partially active' },
    ],
  },

  // ── Oracle ─────────────────────────────────────────────────────────────────
  {
    id: 'subject-meaning',
    name: 'Subject Meaning (Oracle)',
    category: 'Oracle',
    dieType: 100,
    custom: false,
    rows: [
      { min: 1,   max: 2,   result: 'Goals' },
      { min: 3,   max: 4,   result: 'Dreams' },
      { min: 5,   max: 6,   result: 'Environment' },
      { min: 7,   max: 8,   result: 'Outside' },
      { min: 9,   max: 10,  result: 'Inside' },
      { min: 11,  max: 12,  result: 'Reality' },
      { min: 13,  max: 14,  result: 'Allies' },
      { min: 15,  max: 16,  result: 'Enemies' },
      { min: 17,  max: 18,  result: 'Evil' },
      { min: 19,  max: 20,  result: 'Good' },
      { min: 21,  max: 22,  result: 'Emotions' },
      { min: 23,  max: 24,  result: 'Opposition' },
      { min: 25,  max: 26,  result: 'War' },
      { min: 27,  max: 28,  result: 'Peace' },
      { min: 29,  max: 30,  result: 'The innocent' },
      { min: 31,  max: 32,  result: 'Love' },
      { min: 33,  max: 34,  result: 'The spiritual' },
      { min: 35,  max: 36,  result: 'The intellectual' },
      { min: 37,  max: 38,  result: 'New ideas' },
      { min: 39,  max: 40,  result: 'Joy' },
      { min: 41,  max: 42,  result: 'Messages' },
      { min: 43,  max: 44,  result: 'Energy' },
      { min: 45,  max: 46,  result: 'Balance' },
      { min: 47,  max: 48,  result: 'Tension' },
      { min: 49,  max: 50,  result: 'Friendship' },
      { min: 51,  max: 52,  result: 'The physical' },
      { min: 53,  max: 54,  result: 'A project' },
      { min: 55,  max: 56,  result: 'Pleasures' },
      { min: 57,  max: 58,  result: 'Pain' },
      { min: 59,  max: 60,  result: 'Possessions' },
      { min: 61,  max: 62,  result: 'Benefits' },
      { min: 63,  max: 64,  result: 'Plans' },
      { min: 65,  max: 66,  result: 'Lies' },
      { min: 67,  max: 68,  result: 'Expectations' },
      { min: 69,  max: 70,  result: 'Legal matters' },
      { min: 71,  max: 72,  result: 'Bureaucracy' },
      { min: 73,  max: 74,  result: 'Business' },
      { min: 75,  max: 76,  result: 'A path' },
      { min: 77,  max: 78,  result: 'News' },
      { min: 79,  max: 80,  result: 'Exterior factors' },
      { min: 81,  max: 82,  result: 'Randomness' },
      { min: 83,  max: 84,  result: 'Misfortune' },
      { min: 85,  max: 86,  result: 'Death' },
      { min: 87,  max: 88,  result: 'Disruption' },
      { min: 89,  max: 90,  result: 'Power' },
      { min: 91,  max: 92,  result: 'A burden' },
      { min: 93,  max: 94,  result: 'Hard times' },
      { min: 95,  max: 96,  result: 'Failure' },
      { min: 97,  max: 98,  result: 'Decay' },
      { min: 99,  max: 100, result: 'Prior thread' },
    ],
  },
  {
    id: 'random-event-focus',
    name: 'Random Event Focus',
    category: 'Oracle',
    dieType: 10,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'Remote event — something happens far away that affects the story' },
      { min: 2,  max: 2,  result: 'NPC action — an NPC does something unexpected' },
      { min: 3,  max: 3,  result: 'Introduce a new NPC into the scene' },
      { min: 4,  max: 4,  result: 'Move toward a thread — progress on an active thread' },
      { min: 5,  max: 5,  result: 'Move away from a thread — setback on an active thread' },
      { min: 6,  max: 6,  result: 'Close a thread — a thread concludes (good or bad)' },
      { min: 7,  max: 7,  result: 'PC negative — something bad happens to the player character' },
      { min: 8,  max: 8,  result: 'PC positive — something good happens to the player character' },
      { min: 9,  max: 9,  result: 'Ambiguous event — roll Action + Subject to interpret' },
      { min: 10, max: 10, result: 'New entity — a new faction or force enters the story' },
    ],
  },
  {
    id: 'emotion',
    name: 'NPC Emotion / Reaction',
    category: 'NPC',
    dieType: 20,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'Rage — barely contained fury' },
      { min: 2,  max: 2,  result: 'Fear — terrified, wants to flee' },
      { min: 3,  max: 3,  result: 'Grief — deep, raw sadness' },
      { min: 4,  max: 4,  result: 'Joy — genuinely delighted' },
      { min: 5,  max: 5,  result: 'Disgust — openly repulsed' },
      { min: 6,  max: 6,  result: 'Suspicion — watching every move' },
      { min: 7,  max: 7,  result: 'Desperation — will do anything' },
      { min: 8,  max: 8,  result: 'Guilt — clearly hiding something done wrong' },
      { min: 9,  max: 9,  result: 'Pride — arrogant, won\'t be helped' },
      { min: 10, max: 10, result: 'Relief — enormously grateful' },
      { min: 11, max: 11, result: 'Confusion — genuinely doesn\'t understand the situation' },
      { min: 12, max: 12, result: 'Envy — wants what you have' },
      { min: 13, max: 13, result: 'Resignation — given up, going through motions' },
      { min: 14, max: 14, result: 'Excitement — eager, perhaps recklessly so' },
      { min: 15, max: 15, result: 'Contempt — looks down on you openly' },
      { min: 16, max: 16, result: 'Affection — genuinely fond, perhaps uncomfortably so' },
      { min: 17, max: 17, result: 'Boredom — utterly disinterested' },
      { min: 18, max: 18, result: 'Awe — stunned, reverential' },
      { min: 19, max: 19, result: 'Jealousy — sees you as competition or a threat' },
      { min: 20, max: 20, result: 'Calm — unsettlingly composed given the situation' },
    ],
  },
  {
    id: 'monster-appearance',
    name: 'Monster / Creature Appearance',
    category: 'Encounter',
    dieType: 12,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'Chitinous shell, clicking mandibles' },
      { min: 2,  max: 2,  result: 'Rotting flesh, flies and maggots' },
      { min: 3,  max: 3,  result: 'Translucent skin showing organs beneath' },
      { min: 4,  max: 4,  result: 'Covered in eyes of different sizes' },
      { min: 5,  max: 5,  result: 'Wreathed in faint shadow or darkness' },
      { min: 6,  max: 6,  result: 'Scales that refract light oddly' },
      { min: 7,  max: 7,  result: 'Patchwork — body parts of several creatures' },
      { min: 8,  max: 8,  result: 'Feathered, silent, graceful yet wrong' },
      { min: 9,  max: 9,  result: 'Leaving burned/frozen footprints as it moves' },
      { min: 10, max: 10, result: 'Weeping constantly from all orifices' },
      { min: 11, max: 11, result: 'Disguised as something mundane until too close' },
      { min: 12, max: 12, result: 'Disturbingly human, but wrong in small ways' },
    ],
  },
  {
    id: 'rumor',
    name: 'Rumor & Hearsay',
    category: 'Story',
    dieType: 12,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: '"They say a dragon was spotted over the northern peaks"' },
      { min: 2,  max: 2,  result: '"The lord\'s daughter has gone missing — reward offered, no questions"' },
      { min: 3,  max: 3,  result: '"Half the garrison deserted last month. Nobody says why"' },
      { min: 4,  max: 4,  result: '"There\'s a treasure map going cheap at the docks — probably cursed"' },
      { min: 5,  max: 5,  result: '"The old temple is haunted again. Third time this year"' },
      { min: 6,  max: 6,  result: '"A new thieves\' guild is muscling out the old one — blood in the alleys"' },
      { min: 7,  max: 7,  result: '"Merchants avoid the forest road now. Something is picking them off"' },
      { min: 8,  max: 8,  result: '"The healer sells poison to the right buyer"' },
      { min: 9,  max: 9,  result: '"There\'s a secret door in the inn\'s cellar. The innkeeper doesn\'t know"' },
      { min: 10, max: 10, result: '"The new tax collector is pocketing most of it"' },
      { min: 11, max: 11, result: '"Someone\'s been digging up the cemetery at night"' },
      { min: 12, max: 12, result: '"The cult has a list. If your name is on it, you\'ll know soon"' },
    ],
  },
  // ── Wanderer ───────────────────────────────────────────────────────────────
  {
    id: 'wanderer-enemy-roster',
    name: 'Enemy Roster',
    category: 'Wanderer',
    dieType: 10,
    custom: false,
    rows: [
      { min: 1,  max: 2,  result: 'WEAK (Defense 7, Threat d4) — Starving peasant bandit, desperate and poorly armed' },
      { min: 3,  max: 3,  result: 'WEAK (Defense 7, Threat d4) — Goblin scout, cowardly but quick to call friends' },
      { min: 4,  max: 4,  result: 'WEAK (Defense 7, Threat d4) — Animated skeleton, mindless but relentless' },
      { min: 5,  max: 5,  result: 'TOUGH (Defense 10, Threat d6) — City guard, trained and equipped, has backup nearby' },
      { min: 6,  max: 6,  result: 'TOUGH (Defense 10, Threat d6) — Giant wolf, pack hunter — roll oracle: is the pack here?' },
      { min: 7,  max: 7,  result: 'TOUGH (Defense 10, Threat d6) — Mercenary sellsword, professional and ruthless' },
      { min: 8,  max: 8,  result: 'DANGEROUS (Defense 13, Threat d8) — Veteran knight, hardened by a dozen campaigns' },
      { min: 9,  max: 9,  result: 'DANGEROUS (Defense 13, Threat d8) — Troll, regenerates 1 HP/round unless burned' },
      { min: 10, max: 10, result: 'BOSS (Defense 16, Threat d10) — Roll NPC Name + NPC Trait for a named villain' },
    ],
  },
  {
    id: 'wanderer-special-abilities',
    name: 'Special Abilities',
    category: 'Wanderer',
    dieType: 12,
    custom: false,
    rows: [
      { min: 1,  max: 1,  result: 'Iron Hide — Reduce all incoming damage by 1 (min 1)' },
      { min: 2,  max: 2,  result: 'Deadly Strike — Once per combat, deal +3 damage on a hit' },
      { min: 3,  max: 3,  result: 'Shadow Step — Roll EDGE to move unseen past one enemy per scene' },
      { min: 4,  max: 4,  result: 'Arcane Spark — Once per scene, roll WITS vs 10 to cast a d6 damage bolt' },
      { min: 5,  max: 5,  result: 'Battle Hardened — Ignore the first Partial Success condition on each combat roll' },
      { min: 6,  max: 6,  result: 'Survivor — When rolling GRIT at 0 HP, roll twice and take the better result' },
      { min: 7,  max: 7,  result: 'Silver Tongue — Once per scene, reroll a failed social WITS check' },
      { min: 8,  max: 8,  result: 'Hunter\'s Eye — Ranged attacks ignore the Weak defense tier (always hit, just roll damage)' },
      { min: 9,  max: 9,  result: 'Fortitude — Increase Max HP by 3 permanently' },
      { min: 10, max: 10, result: 'Relentless — Recover 1 HP at the start of each new scene (not in combat)' },
      { min: 11, max: 11, result: 'Danger Sense — You are never surprised; always act in the first initiative round' },
      { min: 12, max: 12, result: 'Chosen — Once per session, change any oracle answer to the one you want. Costs 2 Chaos.' },
    ],
  },
  {
    id: 'wanderer-starting-scene',
    name: 'Starting Scene',
    category: 'Wanderer',
    dieType: 8,
    custom: false,
    rows: [
      { min: 1, max: 1, result: 'You wake in a roadside ditch with no memory of last night and your coin purse missing' },
      { min: 2, max: 2, result: 'A dying messenger presses a sealed letter into your hands with their last breath' },
      { min: 3, max: 3, result: 'You arrive at a village that should be busy — it\'s deserted, fires still burning' },
      { min: 4, max: 4, result: 'A bounty notice with your face on it is nailed to the city gate. You didn\'t do it.' },
      { min: 5, max: 5, result: 'You\'re the only survivor of an ambush — and something was taken from the caravan' },
      { min: 6, max: 6, result: 'An old debt comes calling: pay up, fight your way out, or flee into the unknown' },
      { min: 7, max: 7, result: 'A dream led you here — to a ruin that wasn\'t on any map you\'ve seen' },
      { min: 8, max: 8, result: 'You\'ve just been released from prison, wrongly convicted. Your accuser is still out there.' },
    ],
  },
  {
    id: 'wanderer-flaw',
    name: "Wanderer's Flaw",
    category: 'Wanderer',
    dieType: 6,
    custom: false,
    rows: [
      { min: 1, max: 1, result: 'Cursed — Something hunts you. Once per session the GM (oracle) sends something after you.' },
      { min: 2, max: 2, result: 'Wanted — You are a fugitive. Guards and bounty hunters are always a complication.' },
      { min: 3, max: 3, result: 'Debt — You owe someone dangerous. They will collect at the worst possible moment.' },
      { min: 4, max: 4, result: 'Addicted — You require a substance or ritual to function. Without it, −1 to all rolls.' },
      { min: 5, max: 5, result: 'Haunted — A ghost, vision, or voice follows you. Roll WITS vs 10 in tense scenes or freeze.' },
      { min: 6, max: 6, result: 'Marked — A faction wants you dead. Their agents appear whenever the oracle detects doubles.' },
    ],
  },
]

interface TablesStore {
  tables: RandomTable[]
  rollHistory: TableRollResult[]
  addCustomTable: (table: Omit<RandomTable, 'id' | 'custom'>) => void
  deleteCustomTable: (id: string) => void
  rollTable: (tableId: string) => TableRollResult | null
  clearHistory: () => void
}

export const useTablesStore = create<TablesStore>()(
  persist(
    (set, get) => ({
      tables: BUILT_IN_TABLES,
      rollHistory: [],

      addCustomTable: (tableData) => {
        const table: RandomTable = {
          ...tableData,
          id: crypto.randomUUID(),
          custom: true,
        }
        set((s) => ({ tables: [...s.tables, table] }))
      },

      deleteCustomTable: (id) =>
        set((s) => ({ tables: s.tables.filter((t) => t.id !== id || !t.custom) })),

      rollTable: (tableId) => {
        const { tables } = get()
        const table = tables.find((t) => t.id === tableId)
        if (!table) return null
        const roll = Math.floor(Math.random() * table.dieType) + 1
        const row = table.rows.find((r) => roll >= r.min && roll <= r.max)
        const result: TableRollResult = {
          tableId,
          tableName: table.name,
          roll,
          result: row?.result ?? 'No result',
          timestamp: Date.now(),
        }
        set((s) => ({ rollHistory: [result, ...s.rollHistory].slice(0, 100) }))
        return result
      },

      clearHistory: () => set({ rollHistory: [] }),
    }),
    {
      name: 'solo-vtt-tables',
      partialize: (s) => ({
        tables: s.tables.filter((t) => t.custom),
        rollHistory: s.rollHistory,
      }),
      merge: (persisted: any, current) => ({
        ...current,
        tables: [
          ...BUILT_IN_TABLES,
          ...(persisted?.tables ?? []),
        ],
        rollHistory: persisted?.rollHistory ?? [],
      }),
    },
  ),
)
